# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: eardrums_development
  pool: 5
  username: eardrums
  password: eardrums@

test:
  adapter: postgresql
  encoding: unicode
  database: eardrums_new_test
  pool: 5
  username: eardrums_test
  password: eardrums@